# Generated by Django 5.1.3 on 2024-11-12 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authcategory',
            fields=[
                ('authcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('authcategory_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='taxcategory',
            fields=[
                ('taxcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('taxcategory_name', models.CharField(max_length=80)),
                ('taxrate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='templates')),
                ('price', models.IntegerField()),
                ('agelimit', models.BooleanField(default=False)),
                ('soldout', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordersystem.category')),
                ('taxcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordersystem.taxcategory')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('authcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordersystem.authcategory')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordersystem.dish')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordersystem.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordersystem.user')),
            ],
        ),
    ]
